version: 2.1

orbs:
  circleci-cli: circleci/circleci-cli@0.1.8
  orbs: circleci/orb-tools@10.0.0
  general: zeitler/general@0.0.2

workflows:
  main:
    jobs:
      - general/install-dependencies-npm
      - general/lint-commit:
          requires:
            - general/install-dependencies-npm
      - general/lint-json:
          requires:
            - general/install-dependencies-npm
      - general/lint-yaml:
          requires:
            - general/install-dependencies-npm
      - general/lint-circleci-orb:
          requires:
            - general/install-dependencies-npm
      - general/publish-circleci-dev:
          context: Orb Publishing
          orb-ref: zeitler/general
          token-variable: $ORB_PUBLISHING_TOKEN
          requires:
            - general/lint-commit
            - general/lint-json
            - general/lint-yaml
            - general/lint-circleci-orb
          filters:
            branches:
              ignore: master
      - general/create-release-pr:
          context: Release Bot
          git-ssh-fingerprint: d6:86:49:e8:0c:7d:11:a0:ff:3e:ac:75:b0:15:8d:d8
          git-user-email: 18561582+bzeitler69@users.noreply.github.com
          git-user-name: "Release Bot"
          github-access-token: $RELEASE_BOT_GITHUB_TOKEN
          requires:
            - general/lint-commit
            - general/lint-json
            - general/lint-yaml
            - general/lint-circleci-orb
          filters:
            branches:
              only: master
      - general/tag-and-publish-circleci:
          context: Orb Publishing
          git-ssh-fingerprint: d6:86:49:e8:0c:7d:11:a0:ff:3e:ac:75:b0:15:8d:d8
          git-user-email: 18561582+bzeitler69@users.noreply.github.com
          git-user-name: "Release Bot"
          orb-ref: zeitler/general
          token-variable: $ORB_PUBLISHING_TOKEN
          requires:
            - general/lint-commit
            - general/lint-json
            - general/lint-yaml
            - general/lint-circleci-orb
          filters:
            branches:
              only: master
      - general/create-github-release:
          context: Release Bot
          github-access-token: $RELEASE_BOT_GITHUB_TOKEN
          requires:
            - general/tag-and-publish-circleci
          filters:
            branches:
              only: master
