version: 2.1

orbs:
  circleci-cli: circleci/circleci-cli@0.1.1
  orbs: circleci/orb-tools@2.0.2
  general: edahlseng/general@1.1.1

jobs:
  lint-circleci-orb:
    executor: circleci-cli/default
    steps:
      - general/get
      - run: |
          for orb in sources/*; do
            echo "Validating $orb"
            circleci orb validate "$orb"
          done
  publish-circleci-dev:
    executor: circleci-cli/default
    steps:
      - general/get
      - orbs/publish:
          orb-path: sources/general.yml
          orb-ref: edahlseng/general@dev:$(echo "${CIRCLE_BRANCH//[^a-zA-Z0-9-]/-}" | tr '[:upper:]' '[:lower:]')
          token-variable: $ORB_PUBLISHING_TOKEN
  tag-and-publish-circleci:
    executor: circleci-cli/default
    parameters:
      git-ssh-fingerprint:
        type: string
    steps:
      - general/get
      - general/halt-if-not-release-commit
      - add_ssh_keys:
          fingerprints:
            - << parameters.git-ssh-fingerprint >>
      - run:
          name: Setup Git
          command: |
            mkdir -p ~/.ssh

            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
            ' >> ~/.ssh/known_hosts

            git config --global user.email "edahlseng@users.noreply.github.com"
            git config --global user.name "Release Bot"
      - general/tag
      - orbs/publish:
          orb-path: sources/general.yml
          orb-ref: >-
            edahlseng/general@$(git log --format=%B -n 1 $CIRCLE_SHA1 | head -n 1 | sed -r 's/chore\(release\): ([0-9]+\.[0-9]+\.[0-9]+)/\1/')
          token-variable: $ORB_PUBLISHING_TOKEN

workflows:
  main:
    jobs:
      - general/install-dependencies-npm
      - general/lint-commit:
          requires:
            - general/install-dependencies-npm
      - general/lint-json:
          requires:
            - general/install-dependencies-npm
      - general/lint-yaml:
          requires:
            - general/install-dependencies-npm
      - lint-circleci-orb:
          requires:
            - general/install-dependencies-npm
      - publish-circleci-dev:
          context: Orb Publishing
          requires:
            - general/lint-commit
            - general/lint-json
            - general/lint-yaml
            - lint-circleci-orb
          filters:
            branches:
              ignore: master
      - general/create-release-pr:
          context: Release Bot
          ssh-fingerprint: da:75:0b:32:cf:ea:fe:8f:c6:0e:6a:82:6c:fb:c4:78
          requires:
            - general/lint-commit
            - general/lint-json
            - general/lint-yaml
            - lint-circleci-orb
          filters:
            branches:
              only: master
      - tag-and-publish-circleci:
          context: Orb Publishing
          git-ssh-fingerprint: da:75:0b:32:cf:ea:fe:8f:c6:0e:6a:82:6c:fb:c4:78
          requires:
            - general/lint-commit
            - general/lint-json
            - general/lint-yaml
            - lint-circleci-orb
          filters:
            branches:
              only: master
